<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLCASGenDate is an internal mark
   $CLCASGenDate = "1307697518";

/* claro_CasEnabled : If false, other fields are optional */
$GLOBALS['claro_CasEnabled'] = FALSE;


/* claro_CasServerHostUrl : Host of CAS server */
$GLOBALS['claro_CasServerHostUrl'] = 'my.cas.server.domain.com';


/* claro_CasLoginString : Label of the login url to CAS */
$GLOBALS['claro_CasLoginString'] = 'Magic Login';


/* claro_CasServerHostPort : Port of CAS server */
$GLOBALS['claro_CasServerHostPort'] = 443;


/* claro_CasServerRoot : Root folder of CAS (example : 'esup-cas/') */
$GLOBALS['claro_CasServerRoot'] = '';


/* claro_CasGlobalLogout : Logout user from CAS server when user logout from Claroline */
$GLOBALS['claro_CasGlobalLogout'] = FALSE;



?>