<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLAUTHGenDate is an internal mark
   $CLAUTHGenDate = "1307697518";

/* claro_authUsernameCaseSensitive : Choose "No" if you use microsoft active directory (by default this authentication system is case-insensitive) */
$GLOBALS['claro_authUsernameCaseSensitive'] = TRUE;


/* claro_displayLocalAuthForm : If you are not using the local Claroline password to identify a user, disable this option so the access authentication form will not be available */
$GLOBALS['claro_displayLocalAuthForm'] = TRUE;


/* claro_secureLogin : You also need to configure your web server to allow SSL connections to the auth/login.php script ! */
$GLOBALS['claro_secureLogin'] = FALSE;


/* claro_displayLostPasswordLink : Disable this option if you are not using the local Claroline password to identify a user */
$GLOBALS['claro_displayLostPasswordLink'] = TRUE;



?>