<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLANNGenDate is an internal mark
   $CLANNGenDate = "1307697519";

/* announcementPortletMaxItems : Use 0 to display all */
$GLOBALS['announcementPortletMaxItems'] = 3;



?>