<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDOCGenDate is an internal mark
   $CLDOCGenDate = "1307697519";

/* maxFilledSpace_for_course : Disk space allowed to each course */
$GLOBALS['maxFilledSpace_for_course'] = 100000000;


/* maxFilledSpace_for_groups : Disk space allowed to each group */
$GLOBALS['maxFilledSpace_for_groups'] = 1000000;


/* thumbnailWidth : Thumbnail width */
$GLOBALS['thumbnailWidth'] = 75;


/* numberOfRows : Number of rows displayed per page */
$GLOBALS['numberOfRows'] = 3;


/* numberOfCols : Number of columns displayed per page */
$GLOBALS['numberOfCols'] = 4;


/* openNewWindowForDoc : When users click on a document, it opens a new window */
$GLOBALS['openNewWindowForDoc'] = FALSE;


/* cldoc_allowAnonymousToDownloadFolder : This option can be used to prevent web crawlers to download an archive of the folder */
$GLOBALS['cldoc_allowAnonymousToDownloadFolder'] = TRUE;



?>