<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLFRMGenDate is an internal mark
   $CLFRMGenDate = "1307697519";

/* allow_html : Allow user to use html tag in messages */
$GLOBALS['allow_html'] = '1';


/* posts_per_page : Number of posts per page */
$GLOBALS['posts_per_page'] = 5;


/* topics_per_page : Number of topics per page */
$GLOBALS['topics_per_page'] = 5;


/* clfrm_notification_enabled : Enable notification of new items */
$GLOBALS['clfrm_notification_enabled'] = TRUE;


/* clfrm_anonymity_enabled : Choose "Yes" to give course managers the possibility to allow anonymous posting in forums. */
$GLOBALS['clfrm_anonymity_enabled'] = TRUE;


/* confirm_not_anonymous : Choose "Yes" to display a confirmation message when users sign posts in anonymous forums */
$GLOBALS['confirm_not_anonymous'] = TRUE;



?>