<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLGRPGenDate is an internal mark
   $CLGRPGenDate = "1307697518";

/* multiGroupAllowed : Allow teachers to subscribe a user in several groups */
$GLOBALS['multiGroupAllowed'] = TRUE;


/* tutorCanBeSimpleMemberOfOthersGroupsAsStudent : A tutor attached to a group can subscribe himself to another group as a simple user. */
$GLOBALS['tutorCanBeSimpleMemberOfOthersGroupsAsStudent'] = FALSE;


/* showTutorsInGroupList : Not implemented, name reserved  for future version of Claroline */
$GLOBALS['showTutorsInGroupList'] = FALSE;



?>