<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLHOMEGenDate is an internal mark
   $CLHOMEGenDate = "1307697518";

/* course_order_by : Order course by */
$GLOBALS['course_order_by'] = 'official_code';


/* categories_order_by : Order categories by */
$GLOBALS['categories_order_by'] = 'rank';


/* course_categories_hidden_to_anonymous : Hide course categories to anonymous */
$GLOBALS['course_categories_hidden_to_anonymous'] = FALSE;


/* userCourseListGroupByCategories : Group user courses by categories */
$GLOBALS['userCourseListGroupByCategories'] = FALSE;


/* display_former_homepage : Display former Claroline's home page instead of user's desktop */
$GLOBALS['display_former_homepage'] = FALSE;



?>