<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLKCACHEGenDate is an internal mark
   $CLKCACHEGenDate = "1307697518";

/* cache_lifeTime : Time to keep a cache as valid */
$GLOBALS['cache_lifeTime'] = 10;


/* cache_automaticCleaningFactor : write n-1 times without check if (others) cached files are or not deprecated */
$GLOBALS['cache_automaticCleaningFactor'] = 40;



?>