<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLLNPGenDate is an internal mark
   $CLLNPGenDate = "1307697519";

/* maxFilledSpace_for_import : Disk space allowed to import scorm package */
$GLOBALS['maxFilledSpace_for_import'] = 100000000;



?>