<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLMSGGenDate is an internal mark
   $CLMSGGenDate = "1307697518";

/* messagePerPage : Number of message per page */
$GLOBALS['messagePerPage'] = 15;


/* mailNotification : Enable Email notification */
$GLOBALS['mailNotification'] = TRUE;



?>