<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/Se#
		/claroline
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date June 10, 2011 at 01:18 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLCRSGenDate is an internal mark
   $CLCRSGenDate = "1307697518";

/* fill_course_example : Fill courses tools with material example */
$GLOBALS['fill_course_example'] = TRUE;


/* forceCodeCase : You can force the case  of course code */
$GLOBALS['forceCodeCase'] = 'upper';


/* allowPublicCourses : Set to No to avoid the creation of public, world accessible, course sites */
$GLOBALS['allowPublicCourses'] = TRUE;


/* defaultVisibilityOnCourseCreation : This is probably a bad idea to set as hidden */
$GLOBALS['defaultVisibilityOnCourseCreation'] = TRUE;


/* defaultAccessOnCourseCreation : Default course access */
$GLOBALS['defaultAccessOnCourseCreation'] = 'public';


/* defaultRegistrationOnCourseCreation : Default course enrolment */
$GLOBALS['defaultRegistrationOnCourseCreation'] = TRUE;


/* registrationRestrictedThroughCategories : Category's registration restriction */
$GLOBALS['registrationRestrictedThroughCategories'] = FALSE;


/* human_code_needed : User can leave course code (officialCode) field empty or not */
$GLOBALS['human_code_needed'] = TRUE;


/* human_label_needed : User can leave course title field empty or not */
$GLOBALS['human_label_needed'] = TRUE;


/* course_email_needed : User can leave email field empty or not */
$GLOBALS['course_email_needed'] = FALSE;


/* extLinkNameNeeded : Department name */
$GLOBALS['extLinkNameNeeded'] = FALSE;


/* extLinkUrlNeeded : Department website */
$GLOBALS['extLinkUrlNeeded'] = FALSE;


/* prefixAntiNumber : This string is prepend to course database name if it begins with a number */
$GLOBALS['prefixAntiNumber'] = 'No';


/* prefixAntiEmpty : Prefix for empty code course */
$GLOBALS['prefixAntiEmpty'] = 'Course';


/* nbCharFinalSuffix : Length of course code suffix */
/*
Length of suffix added when key is already exist
*/
$GLOBALS['nbCharFinalSuffix'] = 3;


/* showLinkToDeleteThisCourse : Allow course manager to delete their own courses */
$GLOBALS['showLinkToDeleteThisCourse'] = TRUE;



?>